# Service to expose the web app on port 3003
apiVersion: v1
kind: Service
metadata:
  name: insanedemonlist-service
  labels:
    app: insanedemonlist
spec:
  type: LoadBalancer   # Will act like NodePort in Docker Desktop
  selector:
    app: insanedemonlist
  ports:
    - port: 3003              # Port users connect to (can be any number)
      targetPort: 3003      # App's internal port inside the container
      nodePort: 30004
---
# Deployment for your app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insanedemonlist-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: insanedemonlist
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: insanedemonlist
    spec:
      containers:
        - name: insanedemonlist-container
          image: insanedemonlist:latest    # Replace with your custom image
          imagePullPolicy: Always
          ports:
            - containerPort: 3003     # Matches the internal app port